### ISSUE TITLE
Underscore error

### ISSUE THREAD

**Issue by sgentile** [CleverStack/clever-orm#35]
Getting following errors:

clever install clever-orm
Attempting to install clever-orm...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-orm...
  ├── Installing NPM modules for clever-orm...
✔    Successfully installed clever-orm...
  ├── Installing bundledDependencies...
Possibly unhandled TypeError: Object Error: Cannot find module 'underscore' has no method 'match'
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:73:26
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at exports.findGruntFile (/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:91:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:67:9
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at exports.readTasks (/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:62:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:182:9
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at Object.exports.runTasks (/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:181:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:131:46
    at iterate (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:165:9)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:127:39
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at Object.exports.addToMainBundleDeps (/usr/local/lib/node_modules/cleverstack-cli/lib/util/dependencies.js:92:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:124:30
    at done (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:115:33
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at Object.exports.installBundleDeps (/usr/local/lib/node_modules/cleverstack-cli/lib/util/dependencies.js:17:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:113:30
    at /usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:124:9)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:109:23)

**Comment by pilsy** [comment]
@sgentile what version of cleverstack-cli do you have?
`clever -V`

**Comment by sgentile** [comment]
clever --version
1.1.6

**Comment by pilsy** [comment]
Ok that should be fine, is this on a fresh init of the node-seed?

**Comment by sgentile** [comment]
yes - and I'm trying to learn how to setup clever to use postgres

**Comment by pilsy** [comment]
Can you list the commands you ran and their responses please?

**Comment by sgentile** [comment]
I followed the below steps:

http://cleverstack.io/getting-started/   (using OSX instructions)

clever init my-app
clever serve

**Comment by sgentile** [comment]
sorry, I didn't leave the responses - I'll go through it later tonight and validate the responses and report it.

**Comment by pilsy** [comment]
how did you go @sgentile ?
